# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.1.0
  hooks:
  - id: check-yaml
  - id: check-json
  - id: check-toml
  - id: end-of-file-fixer
    exclude: ^(docs/|hypernetx.egg-info/)
  - id: trailing-whitespace
    exclude: ^(docs/|hypernetx.egg-info/|setup.cfg)
  - id: check-merge-conflict
- repo: https://github.com/psf/black
  rev: 24.3.0
  hooks:
  - id: black
